FIREFLY_CONFIG_SECTION = 'FIREFLY'
CONFIG_PORT = 'port'
CONFIG_DEFAULT_PORT = 6002
CONFIG_HOST = 'host'
CONFIG_DEFAULT_HOST = 'localhost'
CONFIG_FILE = 'dev_config/firefly.config'

SERENITY_CONFIG_FILE = 'dev_config/serenity.config'
SERENITY_CONFIG_SECTION = 'SERENITY'